// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Client struct {
	ID        pgtype.UUID
	Name      string
	Phone     pgtype.Text
	CreatedAt pgtype.Timestamp
}

type Loan struct {
	ID                  pgtype.UUID
	ClientID            pgtype.UUID
	Principal           pgtype.Numeric
	MonthlyInterestRate pgtype.Numeric
	Months              int32
	TotalAmount         pgtype.Numeric
	DisbursedAt         pgtype.Timestamp
	CreatedAt           pgtype.Timestamp
}

type Payment struct {
	ID     pgtype.UUID
	LoanID pgtype.UUID
	Amount pgtype.Numeric
	PaidAt pgtype.Timestamp
}
