// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Client struct {
	ID        uuid.UUID
	Name      string
	Phone     sql.NullString
	CreatedAt time.Time
}

type Loan struct {
	ID                  uuid.UUID
	ClientID            uuid.UUID
	Principal           string
	MonthlyInterestRate string
	Months              int32
	TotalAmount         string
	DisbursedAt         time.Time
	CreatedAt           time.Time
}

type Payment struct {
	ID     uuid.UUID
	LoanID uuid.UUID
	Amount string
	PaidAt time.Time
}
